# Copyright (c) 2025, WSO2 LLC. (https://www.wso2.com).
#
# WSO2 LLC. licenses this file to you under the Apache License,
# Version 2.0 (the "License"); you may not use this file except
# in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the
# specific language governing permissions and limitations
# under the License.


name: Build Financial Services Repository

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches:
      - 'main'


jobs:

  Run-Test-Suite:
    runs-on: ubuntu-latest
    env: # Or as an envinment variable
      WSO2_PASSWORD: ${{secrets.SOLUTIONS_BOT_PASSWORD}}
      STMP_ROOT_PASSWORD: ${{secrets.SOLUTIONS_BOT_PASSWORD}}



    steps:
      - uses: actions/checkout@v4
      - name: Run Tests
        run: |            
          
          echo "password is ${{ secrets.SOLUTIONS_BOT_PASSWORD }}"
          echo "username is ${{ secrets.SOLUTIONS_BOT_USERNAME }}"

          echo "password is $WSO2_PASSWORD"
         
          RUNNER_HOME=`pwd`
          TEST_HOME=`pwd`
          
          wget "https://github.com/wso2/product-is/releases/download/v7.0.0/wso2is-7.0.0.zip" -O $TEST_HOME/wso2is-7.0.0.zip
          unzip $TEST_HOME/wso2is-7.0.0.zip -d $TEST_HOME
          name=$(echo "${{ secrets.SOLUTIONS_BOT_USERNAME }}" | cut -d'@' -f1)
          WSO2_UPDATES_HOME=home/$name/.wso2updates
          sudo mkdir -p /home/$name/.wso2-updates/docker && sudo chmod -R 777 /home/$name/.wso2-updates
  
          cp ${RUNNER_HOME}/test-automation/wso2update_linux $TEST_HOME/wso2is-7.0.0/bin/
          ${RUNNER_HOME}/test-automation/wso2update_linux --username ${{ secrets.SOLUTIONS_BOT_USERNAME }} --password ${{ secrets.SOLUTIONS_BOT_PASSWORD }} ||  (${RUNNER_HOME}/test-automation/wso2update_linux --username ${{ secrets.SOLUTIONS_BOT_USERNAME }} --password ${{ secrets.SOLUTIONS_BOT_PASSWORD }} )

      - name: Print password safely
        shell: bash
        env:
          PASSWORD: ${{ secrets.SOLUTIONS_BOT_PASSWORD }}
        run: |
          echo "password is $PASSWORD"

#          {RUNNER_HOME}/test-automation/wso2update_linux
#          bash $RUNNER_HOME/test-automation/test.sh  -u ${{ secrets.SOLUTIONS_BOT_USERNAME }} -p ${{ secrets.SOLUTIONS_BOT_PASSWORD }} -o "$HOME" -h "$HOME"
  






