# Copyright (c) 2024, WSO2 LLC. (https://www.wso2.com).
#
# WSO2 LLC. licenses this file to you under the Apache License,
# Version 2.0 (the "License"); you may not use this file except
# in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the
# specific language governing permissions and limitations
# under the License.

#test
name: Build Financial Services Repository

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    branches:
      - 'main'

jobs:

  Build-repo-check:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Adopt JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11.0.16+8
          distribution: 'temurin'
      - uses: actions/checkout@v3
      - name: Set up Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
#      - name: Cache local Maven repository
#        uses: actions/cache@v4
#        with:
#          path: ~/.m2/repository
#          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
#          restore-keys: |
#            ${{ runner.os }}-maven-
#
#      - name: Setup Maven settings.xml
#        uses: whelk-io/maven-settings-xml-action@v11
#        with:
#          mirrors: >
#            [
#              {
#                "id": "wso2-nexus",
#                "mirrorOf": "wso2-nexus",
#                "url": "http://maven.wso2.org/nexus/content/groups/wso2-public/"
#              },
#              {
#                "id": "wso2.releases",
#                "mirrorOf": "wso2.releases",
#                "url": "http://maven.wso2.org/nexus/content/repositories/releases/"
#              },
#              {
#                "id": "wso2.snapshots",
#                "mirrorOf": "wso2.snapshots",
#                "url": "http://maven.wso2.org/nexus/content/repositories/snapshots/"
#              },
#              {
#                "id": "knopflerfish",
#                "mirrorOf": "knopflerfish",
#                "url": "http://resources.knopflerfish.org/repo/maven2/release"
#              }
#            ]
            
# commented for now
#      - name: Build with Maven
#        run: |
#          export MAVEN_OPTS="-Xmx4g -XX:MaxPermSize=512m"
#          mvn -B install --file pom.xml


      - name: SetUp base Products
        run: |
          mv baseProducts/wso2is-7.0.0 $HOME

      - name: Move the artifacts to the base products
        run: |
          wget https://github.com/ParameswaranSajeenthiran/files/raw/master/wso2-fsiam-accelerator-4.0.0-M3.zip -O wso2-fsiam-accelerator-4.0.0-M3.zip
          cp -r wso2-fsiam-accelerator-4.0.0-M3.zip $HOME/wso2is-7.0.0/
          unzip $HOME/wso2is-7.0.0/wso2-fsiam-accelerator-4.0.0-M3.zip



      - name: Install MySQL 8.0
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-server
          sudo systemctl start mysql
          mysql --version

#      - name: Configure MySQL Database
#        run: |
#          mysql -u root -p'root' -e "
#          CREATE DATABASE IF NOT EXISTS wso2ob;
#          CREATE USER IF NOT EXISTS 'wso2user'@'localhost' IDENTIFIED BY 'wso2password';
#          GRANT ALL PRIVILEGES ON wso2ob.* TO 'wso2user'@'localhost';
#          FLUSH PRIVILEGES;"

      - name: Download and Add MySQL JDBC Driver
        run: |
          wget -q https://repo.maven.apache.org/maven2/mysql/mysql-connector-java/5.1.44/mysql-connector-java-5.1.44.jar
          mv mysql-connector-java-5.1.44.jar $HOME/wso2is-7.0.0/repository/components/lib

#      - name: Configure Identity Server Settings
#        run: |
#          CONFIG_FILE="$HOME/wso2is-7.0.0/wso2-fsiam-accelerator-4.0.0/repository/conf/configure.properties"
##          echo "is_host=localhost" >> "$CONFIG_FILE"
##          echo "admin_username=admin" >> "$CONFIG_FILE"
##          echo "admin_password=admin" >> "$CONFIG_FILE"
##          echo "database_name=wso2ob" >> "$CONFIG_FILE"
##          echo "database_username=wso2user" >> "$CONFIG_FILE"
##          echo "database_password=wso2password" >> "$CONFIG_FILE"

      - name: Verify Configuration
        run: cat $HOME/wso2is-7.0.0/wso2-fsiam-accelerator-4.0.0-M3/repository/conf/configure.properties



